# Reference: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

  build-tags:
    - integration
    - postgres

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/auditumio)
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - goconst
    # Jaeger exporter is deprecated but we still keep it for a while.
    - linters:
        - staticcheck
      text: "^SA1019: \"go.opentelemetry.io/otel/exporters/jaeger\""
