version: v1

managed:
  enabled: true
  go_package_prefix:
    default: github.com/infragmo/auditum/api/gen/go

plugins:
  - name: openapiv2
    strategy: all
    out: api/gen/openapiv2
    opt:
      # See: https://github.com/grpc-ecosystem/grpc-gateway/blob/v2.16.0/protoc-gen-openapiv2/main.go#L18
      - allow_merge=true
      - merge_file_name=auditumio/auditum/v1alpha1/api
      - output_format=yaml
      - disable_service_tags=true
      - openapi_naming_strategy=fqn
      - json_names_for_fields=false
      - simple_operation_ids=true
