name: auditum-local

services:
  postgres:
    container_name: "auditum-local-postgres"
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-auditum_db}
      POSTGRES_USER: ${POSTGRES_USERNAME:-auditum_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-auditum_pass}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - auditum
    volumes:
      - source: postgres-data
        target: /var/lib/postgresql/data
        type: volume
    healthcheck:
      test: pg_isready -d ${POSTGRES_DATABASE:-auditum_db} -U ${POSTGRES_USERNAME:-auditum_user}
      interval: 200ms
      retries: 50
      timeout: 10s

networks:
  auditum:
    name: auditum

volumes:
  postgres-data:
