# Auditum configuration file.

log:
  level: "debug"
  format: "text"

tracing:
  enabled: true
  exporter: otlp
  otlp:
    endpoint: "grpc://localhost:4317"

store:
  type: sqlite

settings:
  records:
    updateEnabled: true
    deleteEnabled: true
    restrictions:
      labels:
        keyMaxSizeBytes: 128
        valueMaxSizeBytes: 512
