/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    // By default, Docusaurus generates a sidebar from the docs folder structure.
    {
      type: 'autogenerated',
      dirName: '.',
    },
    // Additional sections.
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description: 'Explore Auditum API reference.',
        slug: '/reference',
      },
      items: [
        {
          type: 'category',
          label: 'HTTP API',
          items: [
            {
              type: 'link',
              label: 'v1alpha1',
              href: '/reference/redoc/v1alpha1',
            }
          ]
        },
        {
          type: 'category',
          label: 'gRPC API',
          items: [
            {
              type: 'link',
              label: 'v1alpha1',
              href: 'https://github.com/infragmo/auditum/tree/main/api/proto/infragmo/auditum/v1alpha1',
            }
          ]
        }
      ]
    },
  ],
};

module.exports = sidebars;
